% ---------- Delta function (transition) ----------
% delta(CurrentState, ReadSymbol, NextState, WriteSymbol, Move)
delta(5):- {(q0, n0, qf, n0, stay), (q0, n1, qf, n1, stay)}.

% config(State, Head, Position, Symbol, Time)
config(5) :- {(q0, n0, n0, n0, n0)}.
config(Q2, I, I, S2, s(T)) :-
     config(Q, I, I, S, T),
     delta(Q, S, Q2, S2, stay).

config(Q2, I, s(I), S2, s(T)) :-
     config(Q, s(I), s(I), S, T),
     delta(Q, S, Q2, S2, left).

config(Q2, s(I), I, S2, s(T)) :-
     config(Q, I, I, S, T),
     delta(Q, S, Q2, S2, right).

config(Q, I, I2, S, s(T)) :-
     config(Q, I, I2, S, T),
     \+ $eq(I, I2),
     \+ $eq(Q, qf).

 ?- config(qf, H, P, S, T).